# @package _global_
defaults:
  - /model/transformer/finetune: simple_classification
  - /model/transformer/pretrained: ekonbert-base
  # - /model/transformer/pretrained: ekonelectra-base
  - override /task: transformer_finetune
  - override /dataset: finsent_kr

model: 
  transformer:
    finetune:
      config:
        num_train_epochs: 2
        max_seq_length: 256
        train_batch_size: 32
        eval_batch_size: 32
      _pipeline_:
        - train
        # - predict
      prediction:
        data_dir: 
        data_files:
        columns_to_keep:
          - content
          - id
          - classname
        keys:
          input_text: content
 
task:
  name: finsent_kr
