# @package _global_
defaults:
  - /model/transformer/finetune: simple_classification
  - /model/transformer/pretrained: bert-base
  # - /model/transformer/pretrained: ekonelectra-base
  - override /task: transformer_finetune
  - override /dataset: simple

model: 
  transformer:
    finetune:
      config:
        num_train_epochs: 5
        max_seq_length: 128
        train_batch_size: 32
        eval_batch_size: 32
      _pipeline_:
        - train
        # - predict
      prediction:
        data_dir: 
        data_files:
        columns_to_keep:
          - content
          - example_id
          - classname
        keys:
          input_text: content
 
task:
  name: ${oc.select:dataset.name, simple_classification}
