# @package _global_
defaults:
  - override /task: corpus_task

corpus:
  name: esg_report
task:
  verbose: true
  merge_metadata: false
  pipeline:
    _pipeline_:
      tokenize: tokenize
      save_dataframe: save_dataframe
      extract_tokens: extract_tokens
      save_dataframe2: save_dataframe
    tokenize:
      userdic_path: /workspace/projects/eKonPLM/resources/mecab/userdict_ekon.dic
      # preprocessor:
      #   verbose: false
    extract_tokens:
      nouns_only: true
    save_dataframe:
      output_dir: ${dir.project}/esg_report_topic/corpus
      output_file: ${corpus.name}_tokenized.parquet
    save_dataframe2:
      output_dir: ${dir.project}/esg_report_topic/corpus
      output_file: ${corpus.name}_nouns.parquet
